const STORAGE_KEY = "multi-agent-ops-state-v1";
const makeId = () => crypto.randomUUID();
const demoState = { agents: [ { id: makeId(), name: "策略规划 Agent", role: "策略", skills: ["目标拆解", "竞品分析", "排期"], status: "idle", completed: 12 }, { id: makeId(), name: "内容生产 Agent", role: "内容", skills: ["文案", "脚本", "多平台发布"], status: "idle", completed: 26 }, { id: makeId(), name: "数据洞察 Agent", role: "数据", skills: ["报表", "归因", "异常检测"], status: "idle", completed: 18 }, { id: makeId(), name: "客服响应 Agent", role: "客服", skills: ["FAQ", "工单", "情绪识别"], status: "idle", completed: 31 }, { id: makeId(), name: "质检复核 Agent", role: "质检", skills: ["合规", "事实检查", "风险识别"], status: "idle", completed: 16 } ], tasks: [ { id: makeId(), title: "生成本周活动复盘", type: "数据", priority: "高", status: "pending", description: "汇总投放、转化和留存表现", agentId: null, createdAt: Date.now() - 4500000 }, { id: makeId(), title: "编写新品上线推文", type: "内容", priority: "中", status: "pending", description: "适配公众号、小红书和社群", agentId: null, createdAt: Date.now() - 2600000 }, { id: makeId(), title: "处理会员升级咨询", type: "客服", priority: "高", status: "pending", description: "回复高意向用户并标记线索", agentId: null, createdAt: Date.now() - 900000 }, { id: makeId(), title: "检查活动页敏感表述", type: "质检", priority: "中", status: "review", description: "复核广告法风险点", agentId: null, createdAt: Date.now() - 800000 } ], automations: [ { id: makeId(), name: "高优先级自动派单", trigger: "pendingHigh", action: "assignBest", enabled: true }, { id: makeId(), name: "待质检任务提醒", trigger: "qualityNeeded", action: "notifyOps", enabled: true } ], logs: [ { id: makeId(), level: "info", message: "系统初始化完成，等待调度。", time: Date.now() - 300000 } ] };
let state = loadState();
const titles = { dashboard: "运营总览", agents: "Agent 团队", tasks: "任务队列", automations: "自动化规则", logs: "运行日志" };
const views = document.querySelectorAll(".view");
const navItems = document.querySelectorAll(".nav-item");
const emptyTemplate = document.querySelector("#emptyState");
function loadState(){ const saved = localStorage.getItem(STORAGE_KEY); if(!saved) return structuredClone(demoState); try { return JSON.parse(saved); } catch { return structuredClone(demoState); } }
function saveState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function addLog(message, level = "info"){ state.logs.unshift({ id: makeId(), level, message, time: Date.now() }); state.logs = state.logs.slice(0, 120); saveState(); }
function formatTime(timestamp){ return new Intl.DateTimeFormat("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(timestamp); }
function getAgent(agentId){ return state.agents.find((agent) => agent.id === agentId); }
function priorityWeight(priority){ return { 高: 3, 中: 2, 低: 1 }[priority] || 0; }
function pickBestAgent(task){ const candidates = state.agents.filter((agent) => agent.status !== "offline").map((agent) => { const roleScore = agent.role === task.type ? 4 : 0; const skillScore = agent.skills.some((skill) => task.description.includes(skill) || task.title.includes(skill)) ? 2 : 0; const idleScore = agent.status === "idle" ? 2 : 0; return { agent, score: roleScore + skillScore + idleScore - agent.completed * 0.01 }; }).sort((a,b) => b.score - a.score); return candidates[0]?.agent || null; }
function runCycle(){ const enabledRules = state.automations.filter((rule) => rule.enabled); let actions = 0; for(const rule of enabledRules){ if(rule.trigger === "pendingHigh" && state.tasks.some((task) => task.status === "pending" && task.priority === "高")) actions += executeAction(rule); if(rule.trigger === "idleAgent" && state.agents.some((agent) => agent.status === "idle")) actions += executeAction(rule); if(rule.trigger === "qualityNeeded" && state.tasks.some((task) => task.status === "review")) actions += executeAction(rule); } const pendingTasks = state.tasks.filter((task) => task.status === "pending").sort((a,b) => priorityWeight(b.priority) - priorityWeight(a.priority)); for(const task of pendingTasks){ const agent = pickBestAgent(task); if(!agent) continue; task.agentId = agent.id; task.status = "running"; agent.status = "busy"; actions += 1; addLog(`${agent.name} 接收任务：${task.title}`); } const runningTasks = state.tasks.filter((task) => task.status === "running"); for(const task of runningTasks.slice(0, Math.max(1, Math.ceil(runningTasks.length / 2)))){ const agent = getAgent(task.agentId); task.status = task.type === "质检" ? "done" : "review"; if(agent){ agent.status = "idle"; agent.completed += 1; } actions += 1; addLog(`${agent?.name || "Agent"} 完成阶段处理：${task.title}`); } document.querySelector("#cycleStatus").textContent = actions > 0 ? `本轮执行 ${actions} 个动作` : "没有可执行动作"; saveState(); render(); }
function executeAction(rule){ if(rule.action === "assignBest"){ const task = state.tasks.find((item) => item.status === "pending" && (item.priority === "高" || rule.trigger === "idleAgent")); const agent = task ? pickBestAgent(task) : null; if(!task || !agent) return 0; task.agentId = agent.id; task.status = "running"; agent.status = "busy"; addLog(`自动化「${rule.name}」将「${task.title}」分配给 ${agent.name}`); return 1; } if(rule.action === "createQualityTask"){ const source = state.tasks.find((task) => task.status === "review"); if(!source) return 0; state.tasks.push({ id: makeId(), title: `质检复核：${source.title}`, type: "质检", priority: source.priority, status: "pending", description: `复核任务「${source.title}」输出质量`, agentId: null, createdAt: Date.now() }); addLog(`自动化「${rule.name}」创建质检任务`); return 1; } if(rule.action === "notifyOps"){ addLog(`自动化「${rule.name}」触发运营提醒`, "warn"); return 1; } return 0; }
function render(){ renderMetrics(); renderPipeline(); renderAgents(); renderTasks(); renderAutomations(); renderLogs(); }
function renderMetrics(){ document.querySelector("#metricAgents").textContent = state.agents.filter((agent) => agent.status !== "offline").length; document.querySelector("#metricPending").textContent = state.tasks.filter((task) => task.status === "pending").length; document.querySelector("#metricDone").textContent = state.tasks.filter((task) => task.status === "done").length; document.querySelector("#metricAutomations").textContent = state.automations.filter((rule) => rule.enabled).length; }
function renderPipeline(){ const stages = [["pending","待分配"],["running","处理中"],["review","待质检"]]; const pipeline = document.querySelector("#pipeline"); pipeline.innerHTML = stages.map(([status,label]) => { const chips = state.tasks.filter((task) => task.status === status).map((task) => `<div class="task-chip">${escapeHtml(task.title)}</div>`).join(""); return `<div class="stage"><h3>${label}</h3>${chips || '<div class="muted">暂无任务</div>'}</div>`; }).join(""); }
function renderAgents(){ const container = document.querySelector("#agentGrid"); if(!state.agents.length) return setEmpty(container); container.innerHTML = state.agents.map((agent) => `<article class="agent-card"><div class="card-row"><div><h3>${escapeHtml(agent.name)}</h3><div class="muted">${agent.role} · 已完成 ${agent.completed}</div></div><span class="status ${agent.status}">${statusLabel(agent.status)}</span></div><p>${agent.skills.map((skill) => `<span class="tag">${escapeHtml(skill)}</span>`).join(" ")}</p><button class="icon-btn" data-toggle-agent="${agent.id}">切换状态</button> <button class="icon-btn" data-delete-agent="${agent.id}">删除</button></article>`).join(""); }
function renderTasks(){ const container = document.querySelector("#taskList"); if(!state.tasks.length) return setEmpty(container); container.innerHTML = state.tasks.slice().sort((a,b) => priorityWeight(b.priority) - priorityWeight(a.priority) || a.createdAt - b.createdAt).map((task) => { const agent = getAgent(task.agentId); const priorityClass = task.priority === "高" ? "priority-high" : task.priority === "中" ? "priority-mid" : ""; return `<article class="task-item"><div class="task-row"><div><h3>${escapeHtml(task.title)}</h3><div class="muted">${task.type} · <span class="${priorityClass}">${task.priority}优先级</span> · ${taskStatusLabel(task.status)}</div><p>${escapeHtml(task.description)}</p><span class="tag">${agent ? escapeHtml(agent.name) : "未分配"}</span></div><div><button class="icon-btn" data-advance-task="${task.id}">推进</button> <button class="icon-btn" data-delete-task="${task.id}">删除</button></div></div></article>`; }).join(""); }
function renderAutomations(){ const container = document.querySelector("#automationList"); if(!state.automations.length) return setEmpty(container); container.innerHTML = state.automations.map((rule) => `<article class="automation-item"><div class="automation-row"><div><h3>${escapeHtml(rule.name)}</h3><div class="muted">${triggerLabel(rule.trigger)} → ${actionLabel(rule.action)}</div></div><div><button class="icon-btn" data-toggle-rule="${rule.id}">${rule.enabled ? "停用" : "启用"}</button> <button class="icon-btn" data-delete-rule="${rule.id}">删除</button></div></div></article>`).join(""); }
function renderLogs(){ const html = state.logs.map((log) => `<article class="log-item"><strong>${escapeHtml(log.message)}</strong><span class="muted">${formatTime(log.time)} · ${log.level.toUpperCase()}</span></article>`).join(""); document.querySelector("#logList").innerHTML = html || emptyMarkup(); document.querySelector("#recentLogs").innerHTML = html || emptyMarkup(); }
function setEmpty(container){ container.innerHTML = emptyMarkup(); }
function emptyMarkup(){ return emptyTemplate.innerHTML; }
function escapeHtml(value){ return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function statusLabel(status){ return { idle: "空闲", busy: "忙碌", offline: "离线" }[status] || status; }
function taskStatusLabel(status){ return { pending: "待分配", running: "处理中", review: "待质检", done: "已完成" }[status] || status; }
function triggerLabel(trigger){ return { pendingHigh: "出现高优先级待办", idleAgent: "存在空闲 Agent", qualityNeeded: "任务等待质检" }[trigger]; }
function actionLabel(action){ return { assignBest: "分配最匹配 Agent", createQualityTask: "创建质检任务", notifyOps: "记录运营提醒" }[action]; }
document.addEventListener("click", (event) => { const target = event.target; const nav = target.closest(".nav-item"); if(nav){ navItems.forEach((item) => item.classList.toggle("active", item === nav)); views.forEach((view) => view.classList.toggle("active", view.id === nav.dataset.view)); document.querySelector("#viewTitle").textContent = titles[nav.dataset.view]; } if(target.id === "runCycle") runCycle(); if(target.id === "seedDemo"){ state = structuredClone(demoState); addLog("演示数据已重置。"); render(); } if(target.id === "addAgent") document.querySelector("#agentForm").classList.toggle("hidden"); if(target.id === "addTask") document.querySelector("#taskForm").classList.toggle("hidden"); if(target.id === "addAutomation") document.querySelector("#automationForm").classList.toggle("hidden"); if(target.id === "clearLogs"){ state.logs = []; saveState(); render(); } const agentId = target.dataset.toggleAgent; if(agentId){ const agent = getAgent(agentId); agent.status = agent.status === "idle" ? "offline" : "idle"; addLog(`${agent.name} 状态变更为：${statusLabel(agent.status)}`); render(); } const deleteAgentId = target.dataset.deleteAgent; if(deleteAgentId){ state.agents = state.agents.filter((agent) => agent.id !== deleteAgentId); state.tasks.forEach((task) => { if(task.agentId === deleteAgentId) task.agentId = null; }); addLog("已删除一个 Agent。", "warn"); render(); } const taskId = target.dataset.advanceTask; if(taskId){ const task = state.tasks.find((item) => item.id === taskId); task.status = task.status === "pending" ? "running" : task.status === "running" ? "review" : "done"; addLog(`任务「${task.title}」推进到：${taskStatusLabel(task.status)}`); render(); } const deleteTaskId = target.dataset.deleteTask; if(deleteTaskId){ state.tasks = state.tasks.filter((task) => task.id !== deleteTaskId); addLog("已删除一个任务。", "warn"); render(); } const ruleId = target.dataset.toggleRule; if(ruleId){ const rule = state.automations.find((item) => item.id === ruleId); rule.enabled = !rule.enabled; addLog(`自动化「${rule.name}」已${rule.enabled ? "启用" : "停用"}`); render(); } const deleteRuleId = target.dataset.deleteRule; if(deleteRuleId){ state.automations = state.automations.filter((rule) => rule.id !== deleteRuleId); addLog("已删除一条自动化规则。", "warn"); render(); } if(target.id === "exportData"){ const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `agentops-data-${Date.now()}.json`; link.click(); URL.revokeObjectURL(url); } });
document.querySelector("#agentForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); state.agents.push({ id: makeId(), name: form.get("name").trim(), role: form.get("role"), skills: form.get("skills").split(",").map((item) => item.trim()).filter(Boolean), status: "idle", completed: 0 }); event.currentTarget.reset(); event.currentTarget.classList.add("hidden"); addLog("新增 Agent 成功。"); render(); });
document.querySelector("#taskForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); state.tasks.push({ id: makeId(), title: form.get("title").trim(), type: form.get("type"), priority: form.get("priority"), description: form.get("description").trim(), status: "pending", agentId: null, createdAt: Date.now() }); event.currentTarget.reset(); event.currentTarget.classList.add("hidden"); addLog("新增任务成功。"); render(); });
document.querySelector("#automationForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); state.automations.push({ id: makeId(), name: form.get("name").trim(), trigger: form.get("trigger"), action: form.get("action"), enabled: true }); event.currentTarget.reset(); event.currentTarget.classList.add("hidden"); addLog("新增自动化规则成功。"); render(); });
document.querySelector("#importData").addEventListener("change", async (event) => { const file = event.target.files[0]; if(!file) return; const text = await file.text(); state = JSON.parse(text); addLog("数据导入成功。"); render(); });
render();
